import type { Metadata } from "next";
import { Inter, Roboto_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/navbar";
import { UserSync } from "@/components/user-sync";
import { Toaster } from "sonner";
import { getCart } from "@/components/lib/actions/cart";

const notoSans = Noto_Sans({
  variable: '--font-sans',
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await getCart();
  return (
    <ClerkProvider>
      <Navbar cart={cart} />

      <html lang="en" className={notoSans.variable}>
        <body
          className={`${inter.variable} ${robotoMono.variable} antialiased`}
        >
          <UserSync />

          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
